### ISSUE TITLE
Is LFS Supported?

### ISSUE THREAD

**Issue by gabyx** [Arkweid/lefthook#55]
Are the hooks from Git LFS supported?
They probably should be run internally?...

**Comment by Arkweid** [comment]
We support this list of hooks:
https://github.com/Arkweid/lefthook/blob/master/cmd/install.go#L18-L36

**Comment by sr9992** [comment]
I'm trying to get Lefthook to run Git LFS' suggested pre-push hook:
```sh
#!/bin/sh
git lfs pre-push "$@"
```
but when it gets executed by Lefthook, it hangs indefinitely.  I believe this is because `git lfs pre-push` is trying to read from `stdin`, as is documented [here](https://git-scm.com/docs/githooks#_pre_push):
> Information about what is to be pushed is provided on the hook’s standard input with lines of the form:
`<local ref> SP <local sha1> SP <remote ref> SP <remote sha1> LF`

Does Lefthook pass this information to scripts?  Or am I doing something wrong?  Thanks!

**Comment by Arkweid** [comment]
Lefthook pass information from script into. But I don't sure about this case.
You can check `.git/hooks/pre-push` file for debug it.

**Comment by muuvmuuv** [comment]
Still, I think this can be re-opened, git lfs hooks aren't executed and therefore lfs changes aren't pushed to the server. Adding lfs hooks to lefthook does not work, idk what lfs is missing in path, but it exits silently and lefthook will hang. I did not find any workaround yet...

Simple question: would it work importing lfs as a go-mod and use it directly "if it is installed"?

**Comment by gabyx** [comment]
FYI: In https://github.com/gabyx/Githooks we run them internally.

**Comment by muuvmuuv** [comment]
@gabyx cool, thanks! Unfortunately, the reason we use lefthook is that I can easily install it via Homebrew (or others) and with NPM, which we use, since some of our employees use windows and have all kind of problems installing binaries ^^.
